apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: web-deploy
  name: web-deploy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-deploy
status:
  loadBalancer: {}
