apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: 9.30.123.216.traefik.me
    http:
      paths:
      - backend:
          service:
            name: web-deploy
            port:
              number: 80
        path: /
        pathType: Prefix
